<a href="https://colab.research.google.com/github/evukich/Food-Sales-Predictions/blob/main/Food_Sales_Predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
filename = '/content/sales_predictions.csv'
df = pd.read_csv(filename)
df.head(25)

   Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0            FDA15        9.300  ...  Supermarket Type1          3735.1380
1            DRC01        5.920  ...  Supermarket Type2           443.4228
2            FDN15       17.500  ...  Supermarket Type1          2097.2700
3            FDX07       19.200  ...      Grocery Store           732.3800
4            NCD19        8.930  ...  Supermarket Type1           994.7052
5            FDP36       10.395  ...  Supermarket Type2           556.6088
6            FDO10       13.650  ...  Supermarket Type1           343.5528
7            FDP10          NaN  ...  Supermarket Type3          4022.7636
8            FDH17       16.200  ...  Supermarket Type1          1076.5986
9            FDU28       19.200  ...  Supermarket Type1          4710.5350
10           FDY07       11.800  ...  Supermarket Type1          1516.0266
11           FDA03       18.500  ...  Supermarket Type1          2187.1530
12           FDX32       15.100  ...  Supermarket Type1          1589.2646
13           FDS46       17.600  ...  Supermarket Type1          2145.2076
14           FDF32       16.350  ...  Supermarket Type1          1977.4260
15           FDP49        9.000  ...  Supermarket Type1          1547.3192
16           NCB42       11.800  ...  Supermarket Type2          1621.8888
17           FDP49        9.000  ...  Supermarket Type1           718.3982
18           DRI11          NaN  ...  Supermarket Type3          2303.6680
19           FDU02       13.350  ...  Supermarket Type1          2748.4224
20           FDN22       18.850  ...  Supermarket Type1          3775.0860
21           FDW12          NaN  ...  Supermarket Type3          4064.0432
22           NCB30       14.600  ...  Supermarket Type1          1587.2672
23           FDC37          NaN  ...      Grocery Store           214.3876
24           FDR28       13.850  ...  Supermarket Type1          4078.0250

[25 rows x 12 columns]

In [8]:
df.info
#There are 8523 rows and 12 columns

<bound method DataFrame.info of      Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0              FDA15        9.300  ...  Supermarket Type1          3735.1380
1              DRC01        5.920  ...  Supermarket Type2           443.4228
2              FDN15       17.500  ...  Supermarket Type1          2097.2700
3              FDX07       19.200  ...      Grocery Store           732.3800
4              NCD19        8.930  ...  Supermarket Type1           994.7052
...              ...          ...  ...                ...                ...
8518           FDF22        6.865  ...  Supermarket Type1          2778.3834
8519           FDS36        8.380  ...  Supermarket Type1           549.2850
8520           NCJ29       10.600  ...  Supermarket Type1          1193.1136
8521           FDN46        7.210  ...  Supermarket Type2          1845.5976
8522           DRG01       14.800  ...  Supermarket Type1           765.6700

[8523 rows x 12 columns]>

In [9]:
df.dtypes
#These are the data types

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [24]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8518    False
8519    False
8520    False
8521    False
8522    False
Length: 8523, dtype: bool

In [32]:
Item_Weight_missing = df['Item_Weight'].isna()
df.loc[Item_Weight_missing,:]

     Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
7              FDP10          NaN  ...  Supermarket Type3          4022.7636
18             DRI11          NaN  ...  Supermarket Type3          2303.6680
21             FDW12          NaN  ...  Supermarket Type3          4064.0432
23             FDC37          NaN  ...      Grocery Store           214.3876
29             FDC14          NaN  ...      Grocery Store           125.8362
...              ...          ...  ...                ...                ...
8485           DRK37          NaN  ...  Supermarket Type3          6261.8490
8487           DRG13          NaN  ...  Supermarket Type3          4111.3150
8488           NCN14          NaN  ...  Supermarket Type3          2756.4120
8490           FDU44          NaN  ...      Grocery Store           487.3656
8504           NCN18          NaN  ...  Supermarket Type3          4138.6128

[1463 rows x 12 columns]

In [34]:
Outlet_Size_missing = df['Outlet_Size'].isna()
df.loc[Outlet_Size_missing,:]

     Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
3              FDX07       19.200  ...      Grocery Store           732.3800
8              FDH17       16.200  ...  Supermarket Type1          1076.5986
9              FDU28       19.200  ...  Supermarket Type1          4710.5350
25             NCD06       13.000  ...  Supermarket Type1           838.9080
28             FDE51        5.925  ...      Grocery Store           178.4344
...              ...          ...  ...                ...                ...
8502           NCH43        8.420  ...  Supermarket Type1          3020.0688
8508           FDW31       11.350  ...  Supermarket Type1          2587.9646
8509           FDG45        8.100  ...      Grocery Store           424.7804
8514           FDA01       15.000  ...  Supermarket Type1           468.7232
8519           FDS36        8.380  ...  Supermarket Type1           549.2850

[2410 rows x 12 columns]